services:

  postgres:
    image: postgres:16
    container_name: smartflow-postgres
    restart: unless-stopped

    env_file:
      - ../.env

    volumes:
      - smartflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartflow -d smartflow"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    image: node:22-alpine
    container_name: smartflow-backend
    restart: unless-stopped

    working_dir: /app

    volumes:
      - ../backend:/app

    env_file:
      - ../backend/.env

    command: npm run start:dev

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy


volumes:

  smartflow_postgres_data:
